name: First Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  test-pr-build:
    runs-on: [self-hosted, personal-runner]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: 'https://repo.bazaarvoice.com/nexus/content/repositories/npm-all'
          
      - name: Install NPM Dependencies
        working-directory: typescript-todo-list
        run: |
          npm ci
      
      - name: Output
        shell: bash
        run: |
          echo '### Build Summary :rocket:' >> $GITHUB_STEP_SUMMARY
          echo "|  |  |" >> $GITHUB_STEP_SUMMARY
          echo "| **Branch Name**   |  ${{ github.head_ref }}                       |" >> $GITHUB_STEP_SUMMARY
          echo "| **Author**        |  ${{ github.triggering_actor	 }}             |" >> $GITHUB_STEP_SUMMARY
          echo "| **Event Name**    |  ${{ github.event_name }}                     |" >> $GITHUB_STEP_SUMMARY
